---
- name: grub modification
  hosts: nodes
  user: ansible
  become: true
  become_method: sudo
  become_user: root
  vars:
    value: "0"
  tasks:
  - name: Add params
    lineinfile:
      path: /etc/default/grub
      state: present
      backrefs: yes
      regexp: '(^GRUB_CMDLINE_LINUX=.*?)(\bnet\.ifnames=)(\d)(.*)(\bbiosdevname=)(\d)(.*)(\")'
      line: '\1\g<2>{{ value }}\4\g<5>{{ value }}\7\8'

  - name: apply grub2 config
    command:
      cmd: grub2-mkconfig